# Generated by Django 3.2.25 on 2024-03-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(max_length=200),
        ),
    ]
