# Generated by Django 3.2.25 on 2024-03-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_user_fcm_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approveduser',
            old_name='student_id',
            new_name='approveduser_student_id',
        ),
        migrations.RenameField(
            model_name='attendancelist',
            old_name='student_id',
            new_name='attendancelist_student_id',
        ),
    ]
