# Generated by Django 3.2.25 on 2024-03-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20240321_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approveduser',
            name='interest',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='approveduser',
            name='kakao_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='approveduser',
            name='motivation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attendancelist',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
