# Generated by Django 3.2.25 on 2024-03-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_auto_20240321_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
