# Dockerfile

# MySQL 이미지를 기반으로 이미지 생성
FROM mysql:latest

# MySQL 설정
ENV MYSQL_ROOT_PASSWORD=cats1234
ENV MYSQL_DATABASE=cats_db
ENV MYSQL_USER=cats
ENV MYSQL_PASSWORD=cats1234

# 포트 설정 (기본 MySQL 포트는 3306)
EXPOSE 3306
