version: '3'
services:
  mysql:
    container_name: mysql-server
    build:
      context: ./
      dockerfile: Dockerfile_mysql
    volumes:
      - ./mysql/:/var/lib/mysql
      - ./mysql_backup/:/var/lib/mysql_backup
    # command: 
    #   - bash
    #   - -c
    #   - |
    #     mkdir /var/lib/mysql/backup &&
    #     python3 manage.py makemigrations &&
        
    ports:
      - "3306:3306"
  django:
    container_name: django-server
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "0.0.0.0:3306"]  # db 서비스의 상태를 확인하는 테스트
      interval: 10s  # 10초마다 테스트 수행
      retries: 5  # 최대 5번 재시도
      timeout: 5s
    build:
      context: ./
      dockerfile: Dockerfile_django
    volumes:
      - ./django:/home/
    command: 
      - bash
      - -c
      - |
        pip install -r requirements.txt &&
        python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        python3 manage.py makemigrations Api &&
        python3 manage.py migrate &&
        tail -f /dev/null
    ports: 
      - "8000:8000"
    expose:
      - "8000"
