# Generated by Django 3.2.25 on 2024-03-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('uuid', models.IntegerField()),
                ('students_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('fcm_token', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedUser',
            fields=[
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='approved_users', serialize=False, to='TestApp.user')),
                ('gender', models.CharField(max_length=1)),
                ('interest', models.TextField()),
                ('kakao_id', models.CharField(max_length=100)),
                ('motivation', models.TextField()),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='AttedanceList',
            fields=[
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attedance_list', serialize=False, to='TestApp.user')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
