# Generated by Django 3.2.25 on 2024-03-25 11:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Api', '0004_auto_20240325_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('StudentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Api.user')),
                ('ProfileImgURL', models.URLField(max_length=255, null=True)),
                ('PostsCount', models.IntegerField()),
                ('PreferredColor', models.CharField(max_length=20)),
                ('TimeTable', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('PostID', models.AutoField(primary_key=True, serialize=False)),
                ('Caption', models.TextField()),
                ('ImgURL', models.URLField(max_length=255, null=True)),
                ('PostDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('StudentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('LikeID', models.AutoField(primary_key=True, serialize=False)),
                ('PostID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CaTsApp.posts')),
                ('StudentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('CommentID', models.AutoField(primary_key=True, serialize=False)),
                ('CommentText', models.TextField()),
                ('CommentDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('PostID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CaTsApp.posts')),
                ('StudentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Api.user')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('CommentLikeID', models.AutoField(primary_key=True, serialize=False)),
                ('CommentID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CaTsApp.comments')),
                ('StudentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('AttendanceID', models.AutoField(primary_key=True, serialize=False)),
                ('CheckInTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('StudentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Api.user')),
            ],
        ),
    ]
