# Generated by Django 3.2.25 on 2024-03-26 07:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20240326_1617'),
        ('CaTsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSteward',
            fields=[
                ('StockStewardID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemState', models.CharField(choices=[('OB', 'OnBorrow'), ('AFB', 'AvailableForBorrow'), ('NAFB', 'NotAvailableForBorrow')], max_length=4)),
                ('ItemCategory', models.CharField(choices=[('BOOK', 'Book'), ('ED', 'ElectronicDevice'), ('OI', 'OtherItems')], max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='TimeTable',
        ),
        migrations.AddField(
            model_name='attendance',
            name='CheckInDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='TimeTableURL',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='CheckInTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='StudentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.user'),
        ),
        migrations.AlterField(
            model_name='commentlikes',
            name='CommentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaTsApp.comments'),
        ),
        migrations.AlterField(
            model_name='commentlikes',
            name='StudentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.user'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='PostID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaTsApp.posts'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='StudentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.user'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='PostID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaTsApp.posts'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='StudentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.user'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='StudentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.user'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='PreferredColor',
            field=models.CharField(default='#409932', max_length=20),
        ),
        migrations.CreateModel(
            name='FCMLog',
            fields=[
                ('FcmLogID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField()),
                ('Contents', models.TextField()),
                ('Receiver', models.TextField()),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.user')),
            ],
        ),
    ]
