# Generated by Django 3.2.25 on 2024-03-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaTsApp', '0003_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='PostsCount',
        ),
    ]
