# Generated by Django 3.2.25 on 2024-08-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('restaurantName', models.CharField(max_length=255)),
                ('timeOfDay', models.CharField(max_length=255)),
                ('menu', models.CharField(max_length=255)),
            ],
        ),
    ]
