# Generated by Django 3.2.25 on 2024-03-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file', models.FileField(upload_to='uploads/')),
                ('upload_datetime', models.DateTimeField()),
                ('file_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
