# Generated by Django 3.2.25 on 2024-04-01 06:08

import FileHosting.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Api', '0007_remove_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=FileHosting.models.dynamic_upload_path)),
                ('upload_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Api.user')),
            ],
        ),
    ]
