# Generated by Django 3.2.25 on 2024-04-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileHosting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='upload_path',
            field=models.TextField(null=True),
        ),
    ]
