# Generated by Django 3.2.25 on 2024-03-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('StudentId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('GitHubEmail', models.EmailField(max_length=255, null=True)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=6)),
                ('Birthday', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFCMToken',
            fields=[
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='UserFCMToken', serialize=False, to='Api.user')),
                ('FCMToken', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserKakaoInfo',
            fields=[
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='UserKakaoInfo', serialize=False, to='Api.user')),
                ('KakaoUID', models.CharField(max_length=255)),
            ],
        ),
    ]
