# Generated by Django 3.2.25 on 2024-03-25 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfcmtoken',
            name='StudentId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Api.user'),
        ),
        migrations.AlterField(
            model_name='userkakaoinfo',
            name='StudentId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Api.user'),
        ),
    ]
