# Generated by Django 3.2.25 on 2024-03-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20240325_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Auth',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('NONE', 'None')], default=0, max_length=5),
            preserve_default=False,
        ),
    ]
