# Generated by Django 3.2.25 on 2024-03-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20240325_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='PhoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userfcmtoken',
            name='FCMToken',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
